const style=`body{margin:0;background:#fff9f0;color:#302019;font:18px/1.65 system-ui,sans-serif}main{max-width:760px;margin:auto;padding:40px 22px}h1,h2{line-height:1.25}h1{color:#873f2c}a{color:#80351f}nav{display:flex;gap:20px;flex-wrap:wrap}section{margin:32px 0}footer{border-top:1px solid #d9c9b7;padding-top:20px;font-size:15px}`;
const shell=(title:string,body:string)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title} · Jyotara</title><style>${style}</style></head><body><main><nav aria-label="Policies"><a href="/privacy">Privacy policy</a><a href="/delete-account">Delete account</a></nav><h1>${title}</h1>${body}<footer>Jyotara · Innovfix<br>Contact: <a href="mailto:saran@innovfix.in">saran@innovfix.in</a></footer></main></body></html>`;

export function publicPage(path:string):string|null {
  if(path==='/privacy')return shell('Jyotara privacy policy',`
<p>Updated 16 September 2026. This policy explains how Innovfix handles information in Jyotara, our AI astrology app.</p>
<section><h2>Information you provide</h2><p>We process your mobile number to send a sign-in code and identify your account. Our account database stores a protected hash of the number and its last four digits. The SMS provider receives the number and verification code to deliver the message.</p><p>When you create a birth profile or compare profiles, you provide a name or alias, date of birth, optional birth time, selected gender, and birthplace. The chosen place is converted into coordinates for chart calculations. Your questions, relevant recent conversation, chart information and generated answers are processed to provide the requested reading. Do not enter someone else’s information without their permission.</p></section>
<section><h2>Service providers</h2><p>DivineAPI processes birth details and astrology conversations. OpenRouter and the selected Google Gemini model process the question and reading for language and wording. Authkey delivers login SMS messages. These services may process data outside India under their own privacy and retention practices. We do not send your phone number as part of astrology or language requests.</p><p>Information you deliberately include in a question or answer can reveal personal matters. Avoid sharing passwords, identity-document numbers, payment details or other unnecessary sensitive information.</p></section>
<section><h2>Storage and use</h2><p>Saved profiles and chat history are stored in protected storage on your device. Server records support phone login, profile ownership, chart and answer recovery, request limits and service security. Selected chart and answer payloads are encrypted in the server database. Optional research sharing is a separate choice; it is not required to chat. If enabled, it permits the described question and response information to be stored for product improvement.</p><p>When you choose Report answer, the selected answer, guide name and reason are sent for review. Separate birth-profile fields and the rest of the conversation are not automatically attached. Reports are encrypted, kept for up to 90 days, and removed when your account is deleted.</p><p>We do not sell your personal information. This release has no advertising, purchases or active payment collection. We do not request access to your contacts or SMS inbox. Network infrastructure necessarily processes connection information to deliver requests.</p></section>
<section><h2>Your choices and deletion</h2><p>You can edit and delete saved profiles, stop optional research sharing, report an answer, and request account deletion. In the app, open Account and select Delete account. You can also <a href="/delete-account">request deletion without reinstalling the app</a>.</p><p>Account deletion removes the phone account, login sessions, linked chart and answer content, and submitted answer reports from our active database. Deleting through the app also clears that account’s saved data on that device. Copies on another device may require local removal. Minimal security, usage and revocation records may remain temporarily to prevent replay and abuse. Backup copies expire within eight days.</p><p>External astrology conversation deletion is requested separately and can remain pending. A local or server deletion confirmation does not certify that DivineAPI has completed erasure. Contact us to follow up on provider deletion.</p></section>
<section><h2>Young users and AI guidance</h2><p>Jyotara is intended for ages 13 and above. Users under 18 should use it with a parent or guardian’s permission and involvement. Contact us if a child’s information was provided improperly. AI astrology is a traditional interpretation and can be mistaken; it is not proof of another person’s actions or a substitute for medical, legal or financial advice.</p></section>
<section><h2>Contact and updates</h2><p>For access, correction, deletion or privacy concerns, email <a href="mailto:saran@innovfix.in">saran@innovfix.in</a>. We may need to verify account ownership. Do not email an OTP or password. We will update this page when our practices change.</p></section>`);
  if(path==='/delete-account')return shell('Delete your Jyotara account',`
<p>You can request deletion of your Jyotara account and associated data without installing or opening the app.</p>
<section><h2>Request deletion by email</h2><p>Email <a href="mailto:saran@innovfix.in?subject=Jyotara%20account%20deletion%20request">saran@innovfix.in with the subject “Jyotara account deletion request”</a>. Include the mobile number used for Jyotara login and say that you want your account and associated data deleted. Do not send an OTP, password or birth details.</p><p>We may ask you to verify ownership of the phone account before processing the request. We will respond with the verification steps and confirm the outcome. If you no longer have access to the number, explain that in your request.</p></section>
<section><h2>Delete within the app</h2><p>Open Account → Delete account, read the confirmation and confirm deletion. Keep an internet connection until deletion is confirmed. If cleanup is interrupted, reopen the app and retry.</p></section>
<section><h2>What is removed</h2><p>Your phone account, login sessions, linked stored chart and answer content, and submitted answer reports are removed from our active database. The app’s deletion flow also removes saved profiles and chats for that account on the device where you perform it. For an email request, locally stored copies may need removal from your devices separately.</p><p>Minimal security, usage and revocation records may be retained temporarily; backup copies expire within eight days. We request external astrology conversation deletion separately. If the provider has not completed it, we will not describe that copy as erased. Ask us for a status update.</p><p>No payment or subscription cancellation is required for the current free release. See the <a href="/privacy">privacy policy</a> for more information.</p></section>`);
  return null;
}
