import {randomBytes} from 'node:crypto';
// Only server-selected order fields enter this page; never expose account/session credentials.
export function walletCheckoutPage(order:any,key:string){
 const nonce=randomBytes(18).toString('base64');
 const options=JSON.stringify({key,order_id:order.provider_order,amount:Number(order.amount),currency:'INR',name:'Jyotara',description:order.coins+' Jyotara coins',retry:{enabled:false},theme:{color:'#C46B21'}}).replace(/</g,'\\u003c');
 const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Jyotara secure checkout</title><style>body{font:18px system-ui;background:#faf7ef;color:#39271d;text-align:center;padding:40px 16px}button{background:#c46b21;color:white;border:0;border-radius:24px;padding:16px 24px;font-size:18px}#status{margin:24px}</style></head><body><h1>Jyotara</h1><h2>${Number(order.coins)} coins · ₹${Number(order.amount)/100}</h2><p id="status">Opening secure Razorpay checkout…</p><button id="pay">Open Razorpay checkout</button><p>After payment, return to Jyotara. Coins are added after verification.</p><script nonce="${nonce}" src="https://checkout.razorpay.com/v1/checkout.js"></script><script nonce="${nonce}">
const status=document.getElementById('status'),button=document.getElementById('pay');let busy=false,paid=${order.status==='paid'};
async function check(data={}){if(busy||paid)return;busy=true;try{const r=await fetch(location.pathname,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const v=await r.json();if(!r.ok)throw Error();if(v.status==='paid'){paid=true;status.textContent='Payment verified. Coins added. Return to Jyotara.';button.hidden=true;clearInterval(timer);}else if(v.status==='refunded'){status.textContent='This payment was refunded. Return to Jyotara.';button.hidden=true;clearInterval(timer);}else status.textContent='Payment is not confirmed yet. If you paid, do not pay again.';}catch{status.textContent='Could not check payment. Return to Jyotara and refresh your wallet before paying again.';}finally{busy=false;}}
function open(){if(paid)return;try{new Razorpay({...${options},handler:r=>check({paymentId:r.razorpay_payment_id,signature:r.razorpay_signature}),modal:{ondismiss:()=>check()}}).open();}catch{status.textContent='Checkout could not load. Check your connection and try again.';}}
button.onclick=open;const timer=setInterval(()=>{if(!document.hidden)check();},10000);if(paid){status.textContent='Payment verified. Coins added. Return to Jyotara.';button.hidden=true;}else open();
</script></body></html>`;
 return new Response(html,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Referrer-Policy':'no-referrer','Content-Security-Policy':`default-src 'none'; script-src 'nonce-${nonce}' https://checkout.razorpay.com; style-src 'unsafe-inline'; frame-src https://api.razorpay.com https://checkout.razorpay.com; connect-src 'self' https://*.razorpay.com; img-src https://*.razorpay.com data:; base-uri 'none'; frame-ancestors 'none'`}});
}
