import {DatabaseSync} from 'node:sqlite';
import {randomBytes,createHash,scryptSync,timingSafeEqual} from 'node:crypto';
import {chmodSync} from 'node:fs';
const hash=s=>createHash('sha256').update(s).digest('hex');
export class Auth {
 constructor(path){this.db=new DatabaseSync(path);if(path!==':memory:')chmodSync(path,0o600);this.db.exec(`CREATE TABLE IF NOT EXISTS users(email TEXT PRIMARY KEY,salt TEXT NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL); CREATE TABLE IF NOT EXISTS invites(token_hash TEXT PRIMARY KEY,email TEXT NOT NULL,role TEXT NOT NULL,expires INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,email TEXT NOT NULL,expires INTEGER NOT NULL);`);this.attempts=new Map()}
 invite(email,role='viewer'){email=email.trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>160||!['owner','viewer'].includes(role))throw Error('Invalid email');if(this.db.prepare('SELECT 1 FROM users WHERE email=?').get(email))throw Error('Account already exists');const token=randomBytes(32).toString('hex');this.db.prepare('DELETE FROM invites WHERE email=?').run(email);this.db.prepare('INSERT INTO invites VALUES(?,?,?,?)').run(hash(token),email,role,Date.now()+86400000);return token;}
 accept(token,password){if(typeof password!=='string'||password.length<12||password.length>128)throw Error('Use a password of 12–128 characters');const row=this.db.prepare('SELECT * FROM invites WHERE token_hash=? AND expires>?').get(hash(String(token)),Date.now());if(!row)throw Error('Invitation expired or already used');const salt=randomBytes(16).toString('hex');const key=scryptSync(password,salt,64).toString('hex');this.db.exec('BEGIN IMMEDIATE');try{this.db.prepare('INSERT INTO users VALUES(?,?,?,?)').run(row.email,salt,key,row.role);this.db.prepare('DELETE FROM invites WHERE token_hash=?').run(row.token_hash);this.db.exec('COMMIT')}catch(e){this.db.exec('ROLLBACK');throw e}return this.session(row.email);}
 session(email){const token=randomBytes(32).toString('hex');this.db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now());this.db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hash(token),email,Date.now()+8*3600000);return token;}
 login(email,password,ip){if(typeof email!=='string'||typeof password!=='string'||email.length>160||password.length>128)return null;const key=ip;const prior=this.attempts.get(key);const bucket=prior&&prior.until>Date.now()?prior:{count:0,until:Date.now()+15*60000};this.attempts.set(key,bucket);if(++bucket.count>10)throw Error('Too many attempts. Try again in 15 minutes.');if(this.attempts.size>10000)for(const [k,v]of this.attempts)if(v.until<Date.now())this.attempts.delete(k);const row=this.db.prepare('SELECT * FROM users WHERE email=?').get(email.trim().toLowerCase());const actual=scryptSync(password,row?.salt||'invalid-user-fixed-salt',64);const expected=Buffer.from(row?.password_hash||'00'.repeat(64),'hex');if(!timingSafeEqual(actual,expected)||!row)return null;return this.session(row.email);}
 user(cookie){const token=/\bjyotara_dashboard=([a-f0-9]{64})(?:;|$)/.exec(cookie||'')?.[1];if(!token)return null;return this.db.prepare('SELECT u.email,u.role FROM sessions s JOIN users u ON u.email=s.email WHERE s.token_hash=? AND s.expires>?').get(hash(token),Date.now())||null;}
 logout(cookie){const token=/\bjyotara_dashboard=([a-f0-9]{64})(?:;|$)/.exec(cookie||'')?.[1];if(token)this.db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hash(token));}
}
export const sessionCookie=token=>`jyotara_dashboard=${token}; HttpOnly; Secure; SameSite=Strict; Path=/dashboard/; Max-Age=28800`;
